[phases.setup]
nixPkgs = [
  # PHP con extensiones
  "php84.withExtensions",
  "php84Extensions.bcmath",
  "php84Extensions.ctype",
  "php84Extensions.curl",
  "php84Extensions.dom",
  "php84Extensions.fileinfo",
  "php84Extensions.filter",
  "php84Extensions.ftp",
  "php84Extensions.gd",
  "php84Extensions.iconv",
  "php84Extensions.intl",
  "php84Extensions.json",
  "php84Extensions.mbstring",
  "php84Extensions.openssl",
  "php84Extensions.pdo_mysql",
  "php84Extensions.posix",
  "php84Extensions.redis",
  "php84Extensions.simplexml",
  "php84Extensions.soap",
  "php84Extensions.sockets",
  "php84Extensions.sodium",
  "php84Extensions.tokenizer",
  "php84Extensions.xmlwriter",
  "php84Extensions.xsl",
  "php84Extensions.zip",
  "php84Extensions.zlib",

  # Librer√≠as de sistema necesarias
  "libxml2",
  "libzip",
  "zlib",
  "icu",
  "imagemagick"
]

[phases.build]
cmds = [
  "composer create-project --repository-url=https://repo.magento.com/ magento/project-enterprise-edition:2.4.8 magento_enterprise"
]
